import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { ParsedRegionalOffice, ParsedWorkplace } from './validators.ts'

const GENERATED_HEADER = '// AUTO-GENERATED by scripts/import-seed.ts — do not edit manually'

function formatString(value: string): string {
  return JSON.stringify(value)
}

function formatWorkplace(workplace: ParsedWorkplace): string {
  const fields = [
    `id: ${formatString(workplace.id)}`,
    `code: ${formatString(workplace.code)}`,
    `name: ${formatString(workplace.name)}`,
  ]

  if (workplace.shortName) {
    fields.push(`shortName: ${formatString(workplace.shortName)}`)
  }

  return `  { ${fields.join(', ')} }`
}

function formatRegionalOffice(office: ParsedRegionalOffice): string {
  const fields = [
    `id: ${formatString(office.id)}`,
    `code: ${formatString(office.code)}`,
    `name: ${formatString(office.name)}`,
  ]

  if (office.nuts2Code) {
    fields.push(`nuts2Code: ${formatString(office.nuts2Code)}`)
  }

  if (office.nuts2Name) {
    fields.push(`nuts2Name: ${formatString(office.nuts2Name)}`)
  }

  return `  { ${fields.join(', ')} }`
}

export async function writeSeedFiles(
  rootDir: string,
  workplaces: ParsedWorkplace[],
  regionalOffices: ParsedRegionalOffice[],
): Promise<{ workplacesPath: string; regionalOfficesPath: string }> {
  const seedDir = path.join(rootDir, 'src', 'data', 'seed')
  await mkdir(seedDir, { recursive: true })

  const workplacesPath = path.join(seedDir, 'workplaces.ts')
  const regionalOfficesPath = path.join(seedDir, 'regionalOffices.ts')

  const workplacesContent = `${GENERATED_HEADER}
import type { Workplace } from '../../domain/types/workplace'

export const workplaces: Workplace[] = [
${workplaces.map(formatWorkplace).join(',\n')},
]
`

  const regionalOfficesContent = `${GENERATED_HEADER}
import type { RegionalOffice } from '../../domain/types/regionalOffice'

export const regionalOffices: RegionalOffice[] = [
${regionalOffices.map(formatRegionalOffice).join(',\n')}${regionalOffices.length > 0 ? ',' : ''}
]
`

  await writeFile(workplacesPath, workplacesContent, 'utf8')
  await writeFile(regionalOfficesPath, regionalOfficesContent, 'utf8')

  return { workplacesPath, regionalOfficesPath }
}
